version: 2.1

executors:
  clj:
    docker:
      - image: cimg/clojure:1.11.1-openjdk-17.0
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
        
jobs:
  test:
    executor: clj
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "deps.edn" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Dependencies
          command: clojure -X:build/slf4j:deps prep
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "deps.edn" }}
      - run:
          name: Run unit tests
          command: clojure -X:build/slf4j:junit
      - store_test_results:
          path: junit.xml
          
  deploy:
    executor: clj
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "deps.edn" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Dependencies
          command: clojure -X:build/slf4j:deps prep
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "deps.edn" }}
      - when:
          condition: <<pipeline.git.tag>>
          steps:
            - run:
                name: Build Jar
                # Create the jar with the tag as version
                command: clojure -X:build/slf4j:jar :version '"<<pipeline.git.tag>>"'
      - unless:
          condition: <<pipeline.git.tag>>
          steps:
            - run:
                name: Build Jar
                command: clojure -X:build/slf4j:jar
      - run:
          name: Deploy to Clojars
          command: clojure -X:build/slf4j:jar:deploy
          
workflows:
  version: 2
  full-build:
    jobs:
      - test
      - deploy:
          context: clojars
          requires:
            - test
